### PR TITLE
Create GitHub Pages site

### LINKED ISSUE #298: GitHub Pages for docs instead of src/*/README.md
This is an actionable item from the #290 discussion.

Here's how it might happen:

1. Create a docs/ folder
2. Add some PHP server-side pages to the pages/ folder. Specifically:
    - An index home page for a list of all the features
    - A page for each feature that includes a generated OPTIONS table and other boilerplate
4. Use `wget` to **mirror** the localhost:8080 dev served PHP into static HTML tree
5. A GitHub Action to deploy the stuff to GitHub Pages
6. @danielbraun89 enables GitHub Pages in the settings menu of this repo
7. Profit!

Note that you can use literally any framework you want. Next.js, React, Vue, Django, doesn't matter. As long as you can either: 1) statically generate a site natively or 2) use wget or httrack or any other HTTP crawler to download the dynamic HTML and save it as .html files

I think we SHOULD keep the README.md for custom feature-specific details like this example README.md for the ACT feature:

```md
> Run your GitHub Actions locally 🚀

You can find more information about Act on the [nektos/act] GitHub page.

This feature installs the `act` binary to `/usr/local/bin/act` by downloading it
from the [nektos/act] GitHub Releases page. You can set a specific version using
the `version` option in your `devcontainer.json` file. The version you specificy
**must be a valid Git tag** that corresponds to a GitHub Release.

[nektos/act]: https://github.com/nektos/act#readme
```

Here's another example a possible README.md for the DENO feature

```md
> A modern runtime for JavaScript and TypeScript. \
> The easiest, most secure JavaScript runtime.

Details about how to use JavaScript functions provided by Deno is included in the
[Deno Runtime API] docs website. Information on using the CLI is included in
the [Deno manual].

This devcontainer feature is a fork of the [`deno_install`] project. It provides
the heavy lifting of determining which system-specific binary to download, we just
add it to the `$PATH`.

[deno runtime api]: https://deno.land/api
[deno manual]: https://deno.land/manual/getting_started/command_line_interface
[`deno_install`]: https://github.com/denoland/deno_install#readme
```

Note how these README.md files are sorta like the NOTES.md file that the devcontainer/action uses to make PRs? That's the gist that I was going for.

## Why this is good

1. It reduces the PR spam of this repo
2. It makes the docs indexable by Google
3. It lets us reliably change the template that generates the docs (to include our own branding, links, Gitter link, issue link, etc.)

See #290 for more details about how this might relate to other changes

### PR DESCRIPTION
**Pull request by jcbhmr**
Fixes #298 

This PR would... (checkboxes track draft progress)
- [x] Deploy a static site to GitHub Pages
- [x] Add a GitHub Action to deploy to GitHub Pages
- [x] Use PHP and Wget to generate a static site
- [x] Properly install Composer and dependencies
- [x] Add a Composer-specific gitignore file to the docs/ folder
- [x] Segment everything into the docs/ folder as a subproject-like layout
- [x] Create a PHP template for each ID of the src/ folder
- [x] Have an auto-generated HTML table that displays the options
- [ ] Have an auto-generated example of a devcontainer.json

Future ideas for this PHP/HTML page:
- Add a "Need help? Ask on Gitter or GitHub Discussions!" link
- Add a "Encountered a bug? File an Issue!" link
- Add a list of all versions fetched from GitHub Packages
- Highlight the current version
- Add a "Don't see your favorite tool here? Open an Issue or add it yourself!" link on the homepage
- Add some sort of content to the index page besides the list of features

⚠️ @danielbraun89 You'll need to enable GitHub Pages deployments from Actions (currently in public beta) for this GitHub Action to properly work.

image

### CODE REVIEW

**Comment by jcbhmr** [comment]
I'm trying to tackle this again. Hopefully this time the PR that I make doesn't get swallowed in excessive changes or other complications. It's my own fault. 🤷‍♀️ See previous attempt #284.

**Comment by danielbraun89** [comment]
Wow im not an expert on static websites but isnt this a huge effort? 😮 

have changed the Pages to Github action as you suggested 👍

**Comment by jcbhmr** [comment]
@danielbraun89 I already have a proposal for this same basic premise in https://github.com/devcontainers-contrib/templates/pull/15 so it shouldn't be too hard. It's just two PHP pages to generate some static HTML and then a wget or httrack command to crawl and snapshot the dynamic content.

Of course, there are a hundred ways to make it more complex like using Remix, Next.js, React, Vue, Angular, Django, Fastify, Eleventy, etc. but that can all be done **after** a MVP.

@danielbraun89 BTW have you checker Gitter recently? 📬

**Comment by jcbhmr** [comment]
@danielbraun89 Ready to merge! (I hope)

**Pull request closed without merging**
