### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by yf-yang**
See https://github.com/devcontainers/spec/issues/160

Not sure if it was due to a typo before, see https://github.com/devcontainers/cli/issues/163

### CODE REVIEW

**Comment by joshspicer** [comment]
Thanks for flagging! There was a small typo in the spec, which may have perpetuated this.  We have now fixed this.

"`installAfter`" will be ignored by the `devcontainers/cli` tooling - `installsAfter` is correct 👍

**Review by joshspicer — APPROVED** [review]

**Review by ebaskoro — APPROVED** [review]
LGTM

**Comment by jcbhmr** [comment]
I think @danielbraun89 is on Christmas hiatus given his GitHub activity. 😭 Nobody else has merge powers.

**Comment by jcbhmr** [comment]
I think this might be indirectly helping perpetuate #211 too.

**Comment by danielbraun89** [comment]
Wow massive implications for this typo 😭   so thankful for you forr finding this out!

**Pull request merged**
