### PR TITLE
Add more wiki docs

### PR DESCRIPTION
**Pull request by jcbhmr**
This PR will...
1. [x] Add a "The check_packages problem" wiki entry
2. [x] Add the following sections to the "Q&A" wiki entry:
    1. [x] "Which shebang should I use?"
    2. [x] "What is that __dirname variable magic?"
    3. [x] "How do I run part of a feature as a non-root user?"
3. [x] Remove the "Create a feature" guide from the wiki (until further notice)
4. [x] Remove the unfinished "Why is this project structured the way it is?" section from Q&A

@jcbhmr: **For future reference**, here's a hard link to a snapshot of the "Create a feature" page: https://github.com/devcontainers-contrib/features/blob/72f33ed3f0f5654a2840c397269f90ef53891120/wiki/Create-a-feature.md

### CODE REVIEW

**Comment by danielbraun89** [comment]
should I merge it or wait for "ready for review" status?

**Comment by jcbhmr** [comment]
@danielbraun89 still working on it. Currently college Exam Week™. I'll get around to finishing these docs eventually. 👍

**Comment by jcbhmr** [comment]
@danielbraun89 Ready for review 🎉

**Comment by danielbraun89** [comment]
Wow!  This looks terrific thanks 😮

**Comment by danielbraun89** [comment]
> @danielbraun89 still working on it. Currently college Exam Week™. I'll get around to finishing these docs eventually. 👍

Hah! well I hope you put anything college-related as your top priority and not only the exams! good luck 😄

**Pull request merged**
